.TH cmenu 8 cmenu
.SH NAME
cmenu - A lightweight, customizable menu for X
.SH SYNTOPSIS
.B cmenu
[-v] [-b color] [-sb color] [-t color] [-st color] [-f font] [-ip string] [-is string] [-p string]
.SH DESCRIPTION
.B cmenu
is a lightweight, customizable menu for X, inspured by the menu included in the Calm window manager.  newline-delimited arguments are read in from stdin, and are displayed on the screen for the user to choose from.  When a line has been selected,
.B cmenu
will write the chosenline to stdout.  If the provided input matches none of the spllied lines, the input will instead be written to stdout.
.SH OPTIONS
.B -v | --visible
.br
	All items are visible by default.
.br
.br
.B -f | --font
.br
	Specifies a font

.br
.B -fg | --foreground
.br
	Specifies the the foreground color

.br
.B -afg | --active-foreground
.br
	Specifies the active foreground color

.br
.B -bg | --background
.br
	Specifies the background color

.br
.B -sbg | --selected-background
.br
	Specifies the a background color

.br
.B -b | --border
.br
	Specifies the border width

.br
.B -bc | --border-color
.br
	Specifies the border color

.br
.B -p | --padding
.br
	Specifies the inner padding width

.br
.B -pr | --prompt
.br
	Specifies the input prompt

.br
.B -ip --input-prefix
.br
	Specifies the input prefix

.br
.B -is --input-suffix
.br
	Specifies the input suffix
