.TH cmenu 1 cmenu
.SH NAME
cmenu - menu for X
.SH SYNOPSIS
.B cmenu [options]
.SH DESCRIPTION
.B cmenu
is a lightweight and customizable menu for X, based on the menu included in the Calm Window Manager. Input lines are read from stdin and displayed in a menu next to the pointer to click on or search for. When the return key is pressed, the currently highlighted line is written to stdout, and the menu is closed. If no input lines match the search line, then the contents of the search line are instead written to stdout.
.SH OPTIONS
.B -v | --visible
.br
	All items are visible by default

.br
.B -f | --font <font>
.br
	Sets a font, fonts are specified with the X Freetype (XFT) format

.br
.B -fg | --foreground <color>
.br
	Sets the foreground color

.br
.B -bg | --background <color>
.br
	Sets the background color

.br
.B -afg | --active-foreground <color>
.br
	Sets the active foreground color

.br
.B -abg | --active-background <color>
.br
	Sets the active background color

.br
.B -bw | --border-width <width>
.br
	Sets the border width

.br
.B -bc | --border-color <color>
.br
	Sets the border color

.br
.B -p | --padding <width>
.br
	Sets the inner padding witdh for all four sides

.br
.B -pt | --padding-top <width>
.br
.B -pb | --padding-bottom <width>
.br
.B -pl | --padding-left <width>
.br
.B -pr | --padding-right <width>
.br
	Sets the inner padding width for a specific direction

.br
.B -pm | --prompt <string>
.br
	Sets the input prompt

.br
.B -ip | --input-prefix <string>
.br
	Sets the input prefix

.br
.B -is | --input-suffix <string>
.br
	Sets the input suffix
