.TH cmenu 8 cmenu
.SH NAME
cmenu - A scriptable and customizable menu for X
.SH SYNTOPSIS
.B cmenu
[-v] [-b color] [-sb color] [-t color] [-st color] [-f font] [-ip string] [-is string] [-p string]
.SH DESCRIPTION
.B cmenu
is a simple customizable and scriptable window for X, inspired by the menu in the Calm Window Manager. It takes in newline-delimited arguments from stdin, and displays them on screen for the user to pick from. When a line has been selected,
.B cmenu
will write the chosen line (or input) to stdout. If the input provided by the user matches none of the supplied lines, the input will instead be written to stdout.
.SH OPTIONS
.B -v
.br
	all items are visible by default
.br
.B -b <color>
.br
	specifies the window background color
.br
.B -sb <color>
.br
	specifies the selected background color
.br
.B -t <color>
.br
	specifies the foreground color
.br
.B -st <color>
.br
	specifies the selected foreground color
.br
.B -f <font>
.br
	specifies an alternate font
.br
.B -p <string>
.br
	specifies a prompt for the menu
.br
.B -ip <string>
.br
	specifies a prefix string for the input
.br
.B -is <string>
.br
	specifies a suffix string for the input
.br
